### ISSUE TITLE
trying to update a project fails

### ISSUE THREAD

**Issue by bs-github** [SUSE/hackweek#1181] opened 2023-01-19 17:16 UTC
I can not update my project page.
Error message on pressing Update Project:

```
5
(0_0)
0
We're sorry, but something went wrong.
How about you file an issue on github and let us know what you did? That would be AWESOME!

Head back Home
```

I tried to update this page: https://hackweek.opensuse.org/22/projects/open-source-firmware-for-ev-chargers-using-the-esp32-chip-autoaid-slash-en-plus-slash-evsedo/edit

**Comment by bs-github** [comment] 2023-01-20 09:06
I found the char actually provoking the error to be: 🥳

**Comment by hennevogel** [comment] 2023-01-20 10:27
Duplicate of #585

**Closed by hennevogel** 2023-01-20 10:27 UTC
