### ISSUE TITLE
Using unicode explodes the application

### ISSUE THREAD

**Issue by AdamMajer** [SUSE/hackweek#1360] opened 2023-10-24 06:40 UTC
I've tried to use `:smile:` in my description and that exploded its size as per https://github.com/SUSE/hackweek/issues/1359. So then I used the unicode character for it -- `😄` and I got 

![image](https://github.com/SUSE/hackweek/assets/1211498/fc455731-652f-4948-8042-6a456c861fd8)

**Comment by hennevogel** [comment] 2023-10-26 13:37
Duplicate of #585

**Closed by hennevogel** 2023-10-26 13:37 UTC
