### ISSUE TITLE
HW23 project submission does not work, getting an error

### ISSUE THREAD

**Issue by chabowski** [SUSE/hackweek#1361] opened 2023-10-26 13:25 UTC
I cannot submit a HW project. Filling in information, preview is fine, clicking "create project" => error message:

```
5
(0_0)
0
We're sorry, but something went wrong.
How about you [file an issue](https://github.com/SUSE/hackweek/issues) on github and let us know what you did? That would be AWESOME!

Head back [Home](https://hackweek.opensuse.org/)
```

**Comment by hennevogel** [comment] 2023-10-26 13:36
are you using emojis or other Unicode characters? :)

**Comment by chabowski** [comment] 2023-10-26 13:38
Thanks Henne - that might be the issue 😜

**Comment by hennevogel** [comment] 2023-10-26 13:46
👍🏿 

Duplicate of #585

**Closed by hennevogel** 2023-10-26 13:46 UTC
